---
- name: "Verify Satellite Server's CA exists on client"
  stat:
    path: "/etc/pki/ca-trust/source/anchors/katello-server-ca.crt"
  register: "sat6_ca_cert"

- name: "Obtain Satellite Server's CA"
  block:
    - name: "Download CA Certificate"
      get_url:
        url: "http://{{ sat6_capsule | default(sat6_server) }}/pub/katello-server-ca.crt"
        dest: "/etc/pki/ca-trust/source/anchors/katello-server-ca.crt"

    - name: "Update CA trust"
      command: "update-ca-trust"
  when: "not sat6_ca_cert.stat.exists"
  become: True

- name: "Ensure katello-ca-consumer-latest is installed | https"
  yum:
    name: "https://{{ sat6_capsule | default(sat6_server) }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: "present"
  become: True
