---
- name: "Ensure RHN Tools are removed"
  yum:
    name: "{{ sat6_rhn_tools }}"
    state: "absent"

- name: "Ensure RHN System ID is removed"
  file:
    path: "/etc/sysconfig/rhn/systemid"
    state: "absent"

- name: "Cleanup Katello"
  include_tasks: "force-katello.yml"
  when: "sat6_force_katello"

- name: "Ensure katello-ca-consumer-latest is installed"
  yum:
    name: "http://{{ sat6_server }}/pub/katello-ca-consumer-latest.noarch.rpm"
    state: "present"
  when: "not sat6_https"

# For https install of katello-ca-consumer-latest
- name: "Ensure katello-ca-consumer-latest is installed | https"
  include_tasks: "katello-ca-consumer-latest-https.yml"
  when: "sat6_https"

- name: "Register client to Satellite 6"
  redhat_subscription:
    state: "present"
    auto_attach: True
    activationkey: "{{ sat6_activation_key }}"
    org_id: "{{ sat6_organization }}"

- name: "Enable specified repositories"
  shell: 'subscription-manager repos --enable={{ sat6_enable_repos | join(" --enable=") }}'
  when: "sat6_enable_repos|length > 0"

- name: "Ensure katello-agent is installed"
  yum:
    name: "katello-agent"
    state: "latest"

- name: "Ensure goferd (katello-agent) is started and enabled"
  service:
    name: "goferd"
    state: "started"
    enabled: True

- name: "Ensure subscription-manager dependencies are updated"
  yum:
    name: "{{ sat6_sub_mgr_pkgs }}"
    state: "latest"

- name: "Ensure subscription-manager-gnome is removed"
  yum:
    name: "subscription-manager-gnome"
    state: "absent"

- name: "Enable Remote Execution by Distributing foreman-proxy user's public key"
  include_tasks: "rex.yml"
  when: "sat6_remote_execution"

- name: "Satellite 6 Puppet Configuration"
  include_tasks: "puppet.yml"
  tags:
    - "puppet"
  when: "(sat6_puppet) or (sat6_force_puppet)"

- name: "Update Client System"
  yum:
    name: "*"
    state: "latest"
  when: "sat6_update_client"
